-- MySQL Script generated by MySQL Workbench
-- Fri May 21 21:44:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_banco_de_questoes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_banco_de_questoes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_banco_de_questoes` DEFAULT CHARACTER SET utf8 ;
USE `db_banco_de_questoes` ;

-- -----------------------------------------------------
-- Table `db_banco_de_questoes`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco_de_questoes`.`pessoa` (
  `i_id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `s_nome_pessoa` VARCHAR(60) NOT NULL,
  `s_login_pessoa` VARCHAR(80) NOT NULL,
  `s_senha_pessoa` CHAR(32) NOT NULL,
  `b_avatar_pessoa` MEDIUMBLOB,
  `e_tipo_pessoa` ENUM('administrador','professor','aluno') NOT NULL DEFAULT 'aluno',
  PRIMARY KEY (`i_id_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco_de_questoes`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco_de_questoes`.`sala` (
  `i_id_Sala` INT NOT NULL AUTO_INCREMENT,
  `s_nome_sala` VARCHAR(60) NOT NULL,
  `i_id_pessoa_sala` INT NOT NULL,
  PRIMARY KEY (`i_id_Sala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco_de_questoes`.`prova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco_de_questoes`.`prova` (
  `i_id_prova` INT NOT NULL AUTO_INCREMENT,
  `s_cabecalho_prova` TEXT NOT NULL,
  PRIMARY KEY (`i_id_prova`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco_de_questoes`.`sala_prova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco_de_questoes`.`sala_prova` (
  `i_sala` INT NOT NULL,
  `i_prova` INT NOT NULL,
  `sala_i_id_Sala` INT NOT NULL,
  `prova_i_id_prova` INT NOT NULL,
  PRIMARY KEY (`i_sala`, `i_prova`, `sala_i_id_Sala`, `prova_i_id_prova`),
  INDEX `fk_sala_prova_sala1_idx` (`sala_i_id_Sala` ASC) VISIBLE,
  INDEX `fk_sala_prova_prova1_idx` (`prova_i_id_prova` ASC) VISIBLE,
  CONSTRAINT `fk_sala_prova_sala1`
    FOREIGN KEY (`sala_i_id_Sala`)
    REFERENCES `db_banco_de_questoes`.`sala` (`i_id_Sala`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sala_prova_prova1`
    FOREIGN KEY (`prova_i_id_prova`)
    REFERENCES `db_banco_de_questoes`.`prova` (`i_id_prova`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco_de_questoes`.`sala_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco_de_questoes`.`sala_aluno` (
  `i_sala` INT NOT NULL,
  `i_aluno` INT NOT NULL,
  `sala_i_id_Sala` INT NOT NULL,
  `pessoa_i_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`i_sala`, `i_aluno`, `sala_i_id_Sala`, `pessoa_i_id_pessoa`),
  INDEX `fk_sala_aluno_sala1_idx` (`sala_i_id_Sala` ASC) VISIBLE,
  INDEX `fk_sala_aluno_pessoa1_idx` (`pessoa_i_id_pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_sala_aluno_sala1`
    FOREIGN KEY (`sala_i_id_Sala`)
    REFERENCES `db_banco_de_questoes`.`sala` (`i_id_Sala`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sala_aluno_pessoa1`
    FOREIGN KEY (`pessoa_i_id_pessoa`)
    REFERENCES `db_banco_de_questoes`.`pessoa` (`i_id_pessoa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco_de_questoes`.`resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco_de_questoes`.`resposta` (
  `i_id_resposta` INT NOT NULL AUTO_INCREMENT,
  `s_gabarito_resposta` ENUM("a,b,c,d,e") NOT NULL,
  `s_explicacao_resposta` TEXT NOT NULL,
  PRIMARY KEY (`i_id_resposta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco_de_questoes`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco_de_questoes`.`disciplina` (
  `i_id_disciplina` INT NOT NULL AUTO_INCREMENT,
  `s_nome_disciplina` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`i_id_disciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco_de_questoes`.`assunto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco_de_questoes`.`assunto` (
  `i_id_assunto` INT NOT NULL AUTO_INCREMENT,
  `s_nome_assunto` VARCHAR(35) NOT NULL,
  `disciplina_i_id_disciplina` INT NOT NULL,
  PRIMARY KEY (`i_id_assunto`),
  INDEX `fk_assunto_disciplina_idx` (`disciplina_i_id_disciplina` ASC) VISIBLE,
  CONSTRAINT `fk_assunto_disciplina`
    FOREIGN KEY (`disciplina_i_id_disciplina`)
    REFERENCES `db_banco_de_questoes`.`disciplina` (`i_id_disciplina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco_de_questoes`.`questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco_de_questoes`.`questao` (
  `i_id_questao` INT NOT NULL AUTO_INCREMENT,
  `s_enunciado_questao` TEXT NOT NULL,
  `s_comando_questao` TEXT NOT NULL,
  `b_imagem_questao` MEDIUMBLOB,
  `assunto_i_id_assunto` INT NOT NULL,
  `resposta_i_id_resposta` INT NOT NULL,
  PRIMARY KEY (`i_id_questao`),
  
  CONSTRAINT `fk_questao_resposta1`
    FOREIGN KEY (`resposta_i_id_resposta`)
    REFERENCES `db_banco_de_questoes`.`resposta` (`i_id_resposta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_questao_assunto`
    FOREIGN KEY (`assunto_i_id_assunto`)
    REFERENCES `db_banco_de_questoes`.`assunto` (`i_id_assunto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco_de_questoes`.`prova_questoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco_de_questoes`.`prova_questoes` (
  `questao_i_id_questao` INT NOT NULL,
  `prova_i_id_prova` INT NOT NULL,
  PRIMARY KEY (`questao_i_id_questao`, `prova_i_id_prova`),
  INDEX `fk_prova_questoes_questao1_idx` (`questao_i_id_questao` ASC) VISIBLE,
  INDEX `fk_prova_questoes_prova1_idx` (`prova_i_id_prova` ASC) VISIBLE,
  CONSTRAINT `fk_prova_questoes_questao1`
    FOREIGN KEY (`questao_i_id_questao`)
    REFERENCES `db_banco_de_questoes`.`questao` (`i_id_questao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_prova_questoes_prova1`
    FOREIGN KEY (`prova_i_id_prova`)
    REFERENCES `db_banco_de_questoes`.`prova` (`i_id_prova`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco_de_questoes`.`resposta_opcao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco_de_questoes`.`resposta_opcao` (
  `i_resposta_opcao` INT NOT NULL AUTO_INCREMENT,
  `s_item_resposta_opcao` CHAR(1) NOT NULL,
  `s_valor_resposta_opcao` TEXT NOT NULL,
  `resposta_i_id_resposta` INT NOT NULL,
  PRIMARY KEY (`i_resposta_opcao`),
  INDEX `fk_resposta_opcao_resposta1_idx` (`resposta_i_id_resposta` ASC) VISIBLE,
  CONSTRAINT `fk_resposta_opcao_resposta1`
    FOREIGN KEY (`resposta_i_id_resposta`)
    REFERENCES `db_banco_de_questoes`.`resposta` (`i_id_resposta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE VIEW login AS
SELECT
	`i_id_pessoa` AS 'id',
    `s_nome_pessoa` AS 'nome',
    `s_login_pessoa` AS 'login',
    `s_senha_pessoa` AS 'senha',
    `e_tipo_pessoa` AS 'tipo'
FROM `pessoa`
WHERE `i_id_pessoa` = 1


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
